# Imports

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

df = pd.read_csv("../datasets/raw/IndianWeatherRepository.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

# Shape Analysis

In [2]:
rows, cols = df.shape

print(f"Rows: {rows}")
print(f"Columns: {cols}")

# Insight
print("""
Insight:
The dataset contains 119,398 observations and 42 features,
making it sufficiently large for climate analytics,
machine learning, clustering, anomaly detection,
and risk prediction.
""")

Rows: 119398
Columns: 42

Insight:
The dataset contains 119,398 observations and 42 features,
making it sufficiently large for climate analytics,
machine learning, clustering, anomaly detection,
and risk prediction.

# Datatype Analysis

In [3]:
df.dtypes

country                             str
location_name                       str
region                              str
latitude                        float64
longitude                       float64
timezone                            str
last_updated_epoch                int64
last_updated                        str
temperature_celsius             float64
temperature_fahrenheit          float64
condition_text                      str
wind_mph                        float64
wind_kph                        float64
wind_degree                       int64
wind_direction                      str
pressure_mb                       int64
pressure_in                     float64
precip_mm                       float64
precip_in                       float64
humidity                          int64
cloud                             int64
feels_like_celsius              float64
feels_like_fahrenheit           float64
visibility_km                   float64
visibility_miles                  int64
uv_index                          int64
gust_mph                        float64
gust_kph                        float64
air_quality_Carbon_Monoxide     float64
air_quality_Ozone               float64
air_quality_Nitrogen_dioxide    float64
air_quality_Sulphur_dioxide     float64
air_quality_PM2.5               float64
air_quality_PM10                float64
air_quality_us-epa-index          int64
air_quality_gb-defra-index        int64
sunrise                             str
sunset                              str
moonrise                            str
moonset                             str
moon_phase                          str
moon_illumination                 int64
dtype: object

# Datatype Summary

In [4]:
datatype_summary = pd.DataFrame({
    "Column": df.columns,
    "Datatype": df.dtypes.values
})

datatype_summary

                          Column Datatype
0                        country      str
1                  location_name      str
2                         region      str
3                       latitude  float64
4                      longitude  float64
5                       timezone      str
6             last_updated_epoch    int64
7                   last_updated      str
8            temperature_celsius  float64
9         temperature_fahrenheit  float64
10                condition_text      str
11                      wind_mph  float64
12                      wind_kph  float64
13                   wind_degree    int64
14                wind_direction      str
15                   pressure_mb    int64
16                   pressure_in  float64
17                     precip_mm  float64
18                     precip_in  float64
19                      humidity    int64
20                         cloud    int64
21            feels_like_celsius  float64
22         feels_like_fahrenheit  float64
23                 visibility_km  float64
24              visibility_miles    int64
25                      uv_index    int64
26                      gust_mph  float64
27                      gust_kph  float64
28   air_quality_Carbon_Monoxide  float64
29             air_quality_Ozone  float64
30  air_quality_Nitrogen_dioxide  float64
31   air_quality_Sulphur_dioxide  float64
32             air_quality_PM2.5  float64
33              air_quality_PM10  float64
34      air_quality_us-epa-index    int64
35    air_quality_gb-defra-index    int64
36                       sunrise      str
37                        sunset      str
38                      moonrise      str
39                       moonset      str
40                    moon_phase      str
41             moon_illumination    int64

# Missing Value Analysis

In [5]:
missing_values = df.isnull().sum()
missing_values

country                         0
location_name                   0
region                          0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

# Missing Value Report

In [6]:
total_missing = missing_values.sum()

print("Total Missing Values:", total_missing)

# Insight
print("""
Insight:
No missing values were found.
No imputation is required.
Data quality is excellent.
""")

Total Missing Values: 0

Insight:
No missing values were found.
No imputation is required.
Data quality is excellent.

# Duplicate Analysis

In [7]:
duplicates = df.duplicated().sum()

print("Duplicate Records:", duplicates)

# Insight

print("""
Insight:
No duplicate observations exist.
Dataset integrity is maintained.
""")

Duplicate Records: 0

Insight:
No duplicate observations exist.
Dataset integrity is maintained.

# Numerical vs Categorical Segmentation

In [8]:
numerical_columns = df.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_columns = df.select_dtypes(
    include=["object", "string"]
).columns

print("Numerical Features:", len(numerical_columns))
print("Categorical Features:", len(categorical_columns))

Numerical Features: 30
Categorical Features: 12

# Categorical Features

In [9]:
pd.DataFrame({
    "Categorical Features": categorical_columns
})

   Categorical Features
0               country
1         location_name
2                region
3              timezone
4          last_updated
5        condition_text
6        wind_direction
7               sunrise
8                sunset
9              moonrise
10              moonset
11           moon_phase

# Descriptive Statistics

In [10]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,precip_mm,precip_in,humidity,cloud,feels_like_celsius,feels_like_fahrenheit,visibility_km,visibility_miles,uv_index,gust_mph,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,119398.000000,119398.000000,1.193980e+05,119398.000000,119398.00000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000,119398.000000
mean,23.099620,80.246300,1.702939e+09,20.303723,68.54687,5.024552,8.090798,157.507044,1012.828196,29.908350,0.084331,0.003253,61.582681,23.531600,20.955116,69.712328,8.625313,5.086668,1.084742,9.845152,15.844931,773.096727,43.775466,14.507559,6.650753,92.161884,109.530122,3.262349,6.621007,52.458282
std,5.791228,5.763446,5.659113e+06,6.538599,11.76929,2.825159,4.538947,115.412587,4.926352,0.145307,0.608602,0.023960,23.619385,29.774276,7.468814,13.443341,2.794805,1.833549,0.704080,4.968244,7.993618,654.566069,30.633582,15.625656,13.329390,96.278193,108.621703,1.412098,3.489160,34.809059
min,7.170000,68.970000,1.693286e+09,-30.700000,-23.30000,2.200000,3.600000,1.000000,991.000000,29.280000,0.000000,0.000000,8.000000,0.000000,-36.500000,-33.800000,0.000000,0.000000,1.000000,0.000000,0.000000,113.500000,0.000000,0.000000,0.000000,0.500000,0.500000,1.000000,1.000000,0.000000
25%,20.270000,76.070000,1.697921e+09,16.600000,61.90000,2.700000,4.300000,54.000000,1010.000000,29.830000,0.000000,0.000000,42.000000,1.000000,16.600000,61.800000,10.000000,6.000000,1.000000,6.100000,9.800000,413.900000,19.500000,5.200000,1.600000,30.400000,41.200000,2.000000,3.000000,18.000000
50%,23.950000,78.690000,1.703098e+09,21.200000,70.20000,4.300000,6.800000,124.000000,1013.000000,29.930000,0.000000,0.000000,63.000000,8.000000,21.200000,70.200000,10.000000,6.000000,1.000000,8.900000,14.400000,580.800000,39.300000,10.000000,3.500000,60.600000,75.600000,3.000000,8.000000,53.000000
75%,26.770000,83.900000,1.707760e+09,24.900000,76.80000,6.500000,10.400000,272.000000,1016.000000,30.000000,0.000000,0.000000,83.000000,41.000000,26.200000,79.200000,10.000000,6.000000,1.000000,13.000000,20.900000,921.300000,63.700000,18.900000,7.000000,117.600000,138.500000,4.000000,10.000000,88.000000
max,34.570000,95.800000,1.718557e+09,42.800000,109.10000,26.800000,43.200000,360.000000,1073.000000,31.690000,43.800000,1.720000,100.000000,100.000000,50.500000,122.900000,10.000000,6.000000,9.000000,51.000000,82.200000,13565.100000,243.200000,318.100000,557.000000,1374.800000,1537.800000,6.000000,10.000000,100.000000

# Categorical Statistics

In [11]:
df.describe(include=["object", "string"])

       country location_name         region      timezone    last_updated condition_text wind_direction  sunrise   sunset     moonrise     moonset      moon_phase
count   119398        119398         119398        119398          119398         119398         119398   119398   119398       119398      119398          119398
unique       1           552             33             3             877             50             16      202      215         1441        1441               8
top      India         Nagar  Uttar Pradesh  Asia/Kolkata  04-02-24 23:00          Clear              N  6:17 AM  6:01 PM  No moonrise  No moonset  Waning Gibbous
freq    119398           461          13293        118745             548          47978          12987     1597     1538         4389        3836           28478

# Unique Value Analysis

In [12]:
summary = pd.DataFrame({
    "Column": df.columns,
    "Datatype": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Unique Values": df.nunique().values
})
summary

                          Column Datatype  Missing Values  Unique Values
0                        country      str               0              1
1                  location_name      str               0            552
2                         region      str               0             33
3                       latitude  float64               0            455
4                      longitude  float64               0            435
5                       timezone      str               0              3
6             last_updated_epoch    int64               0            432
7                   last_updated      str               0            877
8            temperature_celsius  float64               0            636
9         temperature_fahrenheit  float64               0           1056
10                condition_text      str               0             50
11                      wind_mph  float64               0            103
12                      wind_kph  float64               0            103
13                   wind_degree    int64               0            360
14                wind_direction      str               0             16
15                   pressure_mb    int64               0             72
16                   pressure_in  float64               0            173
17                     precip_mm  float64               0            534
18                     precip_in  float64               0             72
19                      humidity    int64               0             93
20                         cloud    int64               0            101
21            feels_like_celsius  float64               0            695
22         feels_like_fahrenheit  float64               0           1162
23                 visibility_km  float64               0             44
24              visibility_miles    int64               0              7
25                      uv_index    int64               0              9
26                      gust_mph  float64               0            363
27                      gust_kph  float64               0            554
28   air_quality_Carbon_Monoxide  float64               0            416
29             air_quality_Ozone  float64               0            384
30  air_quality_Nitrogen_dioxide  float64               0            391
31   air_quality_Sulphur_dioxide  float64               0            409
32             air_quality_PM2.5  float64               0           5078
33              air_quality_PM10  float64               0           5561
34      air_quality_us-epa-index    int64               0              6
35    air_quality_gb-defra-index    int64               0             10
36                       sunrise      str               0            202
37                        sunset      str               0            215
38                      moonrise      str               0           1441
39                       moonset      str               0           1441
40                    moon_phase      str               0              8
41             moon_illumination    int64               0             92

# Initial Climate Insights Report

In [13]:
print("""
CLIMATE INSIGHTS REPORT

1. Dataset contains 119,398 environmental observations.

2. Dataset covers 552 unique locations across India.

3. Dataset includes 33 regions/states.

4. Dataset contains weather, air quality,
   geographical, temporal, and astronomical data.

5. No missing values detected.

6. No duplicate records detected.

7. Air quality indicators available:
   - PM2.5
   - PM10
   - Carbon Monoxide
   - Ozone
   - Nitrogen Dioxide
   - Sulphur Dioxide

8. Weather indicators available:
   - Temperature
   - Humidity
   - Pressure
   - Wind
   - Precipitation
   - Visibility
   - UV Index

9. Dataset is suitable for:
   - Climate Profiling
   - Anomaly Detection
   - Rainfall Risk Prediction
   - Heatwave Risk Prediction
   - Climate Risk Scoring
   - Explainable AI
""")


# yyy

CLIMATE INSIGHTS REPORT

1. Dataset contains 119,398 environmental observations.

2. Dataset covers 552 unique locations across India.

3. Dataset includes 33 regions/states.

4. Dataset contains weather, air quality,
   geographical, temporal, and astronomical data.

5. No missing values detected.

6. No duplicate records detected.

7. Air quality indicators available:
   - PM2.5
   - PM10
   - Carbon Monoxide
   - Ozone
   - Nitrogen Dioxide
   - Sulphur Dioxide

8. Weather indicators available:
   - Temperature
   - Humidity
   - Pressure
   - Wind
   - Precipitation
   - Visibility
   - UV Index

9. Dataset is suitable for:
   - Climate Profiling
   - Anomaly Detection
   - Rainfall Risk Prediction
   - Heatwave Risk Prediction
   - Climate Risk Scoring
   - Explainable AI